export const TRACKED_DOMAINS = ["facebook.com", "youtube.com"] as const;
export const SESSION_LENGTH_SECONDS = 10 * 60; // 10 minutes
export const DAY_START_HOUR = 5; // 5 AM
export const TICK_INTERVAL_SECONDS = 30;
export const IDLE_THRESHOLD_SECONDS = 120; // 2 minutes
export const COUNTDOWN_SECONDS = 5;
export const ALARM_NAME = "antiprocra-tick";
export const PAUSE_GRACE_SECONDS = 120;
export const PAUSE_ALARM_PREFIX = "antiprocra-pause-";
